all: client server sequential forking 10000 threads threads-sem threadpool

CLFAGS += -pthread

client: csapp.o
server: csapp.o
sequential: csapp.o
forking: csapp.o
threaded: csapp.o
threadpool: csapp.o
